name: Deploy FastAPI App to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest -v
        continue-on-error: true

      - name: Archive source code for deployment
        run: |
          zip -r app.zip . -x '*.git*' '*.pytest_cache*' '__pycache__/*'
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_package
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Node.js (for CDK)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install AWS CDK
        run: npm install -g aws-cdk@2.139.0

      - name: Set up Python & Poetry for CDK
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root

      - name: Deploy infrastructure with CDK
        run: |
          cdk bootstrap aws://${{ env.AWS_ACCESS_KEY_ID }}@${{ env.AWS_REGION }}
          cdk deploy --all --require-approval never
        shell: bash
